org: lukejgaskell
app: represent
service: backend

frameworkVersion: "2"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  stage: dev
  region: us-east-1
  environment:
    SUPABASE_SERVICE_KEY: ${param:supabaseServiceKey}
    API_KEY: ${param:proPublicaAPIKey}

functions:
  syncVotes:
    handler: votes-sync.handler.run
    events:
      - schedule: cron(0 12,20 ? * * *)
  syncMembers:
    handler: members-sync.handler.run
    timeout: 30
    events:
      - schedule: cron(0 12 ? * * *)
