FROM node:alpine
WORKDIR /app

# add required packages for gatsby
RUN apk update && apk add build-base autoconf automake libtool pkgconfig nasm

# COPY the package.json file, update any deps and install them
COPY package.json .
COPY package-lock.json .
RUN npm install

# copy the whole source folder(the dir is relative to the Dockerfile
COPY . .

CMD [ "npm", "run", "develop-docker" ]