version: "3"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src 
      - ./static:/app/static # Links the source files to the running container
    ports:
      - "3000:8000"