org: lukejgaskell
app: represent
service: backend

frameworkVersion: "2"

custom:
  votesTableName: "votes-table-${self:provider.stage}"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [VotesTable, Arn]
  environment:
    VOTES_TABLE: ${self:custom.votesTableName}
    API_KEY: ${param:proPublicaAPIKey}

functions:
  pullVotes:
    handler: handler.run
    events:
      - schedule: rate(2 hours)

resources:
  Resources:
    VotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: yearMonth
            AttributeType: S
          - AttributeName: dateTime
            AttributeType: S
        KeySchema:
          - AttributeName: yearMonth
            KeyType: HASH
          - AttributeName: dateTime
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.votesTableName}
